/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTransactionRouteImport } from './routes/admin/transaction'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminCustomerRouteImport } from './routes/admin/customer'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionRoute = AdminTransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomerRoute = AdminCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/customer': typeof AdminCustomerRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/customer': typeof AdminCustomerRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/customer': typeof AdminCustomerRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/transaction': typeof AdminTransactionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/customer'
    | '/admin/inventory'
    | '/admin/transaction'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/customer'
    | '/admin/inventory'
    | '/admin/transaction'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/customer'
    | '/admin/inventory'
    | '/admin/transaction'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transaction': {
      id: '/admin/transaction'
      path: '/transaction'
      fullPath: '/admin/transaction'
      preLoaderRoute: typeof AdminTransactionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customer': {
      id: '/admin/customer'
      path: '/customer'
      fullPath: '/admin/customer'
      preLoaderRoute: typeof AdminCustomerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCustomerRoute: typeof AdminCustomerRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminTransactionRoute: typeof AdminTransactionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomerRoute: AdminCustomerRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminTransactionRoute: AdminTransactionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
